// <auto-generated />
namespace OSL_B2.Inventory.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202210250359437_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
